// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package straddle

import (
	"context"
	"fmt"
	"net/http"

	"github.com/stainless-sdks/straddle-go/internal/apijson"
	"github.com/stainless-sdks/straddle-go/internal/param"
	"github.com/stainless-sdks/straddle-go/internal/requestconfig"
	"github.com/stainless-sdks/straddle-go/option"
	"github.com/stainless-sdks/straddle-go/shared"
)

// BridgeLinkService contains methods and other services that help with interacting
// with the straddle API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewBridgeLinkService] method instead.
type BridgeLinkService struct {
	Options []option.RequestOption
}

// NewBridgeLinkService generates a new service that applies the given options to
// each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewBridgeLinkService(opts ...option.RequestOption) (r *BridgeLinkService) {
	r = &BridgeLinkService{}
	r.Options = opts
	return
}

// Use Bridge to create a new paykey using a bank routing and account number as the
// source. This endpoint allows you to create a secure payment token linked to a
// specific bank account.
func (r *BridgeLinkService) BankAccount(ctx context.Context, params BridgeLinkBankAccountParams, opts ...option.RequestOption) (res *shared.PaykeyV1ItemResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%s", params.CorrelationID)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%s", params.RequestID)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%s", params.StraddleAccountID)))
	}
	opts = append(r.Options[:], opts...)
	path := "v1/bridge/bank_account"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, params, &res, opts...)
	return
}

// Use Bridge to create a new paykey using a Plaid token as the source. This
// endpoint allows you to create a secure payment token linked to a bank account
// authenticated through Plaid.
func (r *BridgeLinkService) Plaid(ctx context.Context, params BridgeLinkPlaidParams, opts ...option.RequestOption) (res *shared.PaykeyV1ItemResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%s", params.CorrelationID)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%s", params.RequestID)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%s", params.StraddleAccountID)))
	}
	opts = append(r.Options[:], opts...)
	path := "v1/bridge/plaid"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, params, &res, opts...)
	return
}

type BridgeLinkBankAccountParams struct {
	// The bank account number.
	AccountNumber param.Field[string]               `json:"account_number,required"`
	AccountType   param.Field[shared.AccountTypeV1] `json:"account_type,required"`
	// Unique identifier of the related customer object.
	CustomerID param.Field[string] `json:"customer_id,required" format:"uuid"`
	// The routing number of the bank account.
	RoutingNumber param.Field[string] `json:"routing_number,required"`
	// Up to 20 additional user-defined key-value pairs. Useful for storing additional
	// information about the paykey in a structured format.
	Metadata          param.Field[map[string]string] `json:"metadata"`
	CorrelationID     param.Field[string]            `header:"Correlation-Id"`
	RequestID         param.Field[string]            `header:"Request-Id"`
	StraddleAccountID param.Field[string]            `header:"Straddle-Account-Id" format:"uuid"`
}

func (r BridgeLinkBankAccountParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type BridgeLinkPlaidParams struct {
	// Unique identifier of the related customer object.
	CustomerID param.Field[string] `json:"customer_id,required" format:"uuid"`
	// Plaid processor token generated by your application for use with the Straddle
	// API.
	PlaidToken param.Field[string] `json:"plaid_token,required"`
	// Up to 20 additional user-defined key-value pairs. Useful for storing additional
	// information about the paykey in a structured format.
	Metadata          param.Field[map[string]string] `json:"metadata"`
	CorrelationID     param.Field[string]            `header:"Correlation-Id"`
	RequestID         param.Field[string]            `header:"Request-Id"`
	StraddleAccountID param.Field[string]            `header:"Straddle-Account-Id" format:"uuid"`
}

func (r BridgeLinkPlaidParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
